from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from companion.lock import state_lock


_TIMESTAMP = "%Y-%m-%d_%H%M%S"
_RESERVED_NAMES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{number}" for number in range(1, 10)),
    *(f"LPT{number}" for number in range(1, 10)),
}


def prepare_call(root: Path, spec: dict[str, Any], now: datetime) -> dict[str, Any]:
    root = Path(root).resolve()
    if now.tzinfo is None:
        raise ValueError("creation time must include a timezone")

    subject = str(spec.get("subject", "")).strip()
    slug = _subject_slug(subject)
    request_id = str(spec.get("request_id", "")).strip()
    if not request_id:
        raise ValueError("request_id is required")
    expected_main = _safe_name(
        str(spec.get("expected_main_json", "")), "expected main JSON filename"
    )
    if Path(expected_main).suffix.casefold() != ".json":
        raise ValueError("expected main JSON filename must end in .json")
    prompt_text = spec.get("prompt_text")
    if not isinstance(prompt_text, str) or not prompt_text.strip():
        raise ValueError("prompt_text is required")
    input_files = spec.get("input_files")
    if not isinstance(input_files, list) or not input_files:
        raise ValueError("input_files must be a non-empty list")

    timestamp = now.strftime(_TIMESTAMP)
    exchange_id = f"{timestamp}_{slug}"
    prompt_name = f"PROMPT_{timestamp}.txt"
    calls_dir = root / "calls"
    state_dir = root / "state"
    destination = calls_dir / exchange_id
    if destination.exists():
        raise FileExistsError(f"exchange already exists: {exchange_id}")

    prepared_inputs: list[tuple[Path, str]] = []
    seen = {prompt_name.casefold()}
    for item in input_files:
        if not isinstance(item, dict):
            raise ValueError("each input file must be an object")
        source_text = item.get("path")
        if not isinstance(source_text, str) or not source_text.strip():
            raise ValueError("input file path is required")
        source = Path(source_text).expanduser()
        try:
            source = source.resolve(strict=True)
        except FileNotFoundError as error:
            raise FileNotFoundError(f"input file does not exist: {source.name}") from error
        if not source.is_file():
            raise ValueError(f"input path is not a regular file: {source.name}")
        packaged_name = _safe_name(
            str(item.get("filename", "")), "input filename"
        )
        if packaged_name.upper().startswith("PROMPT_"):
            raise ValueError("PROMPT files are generated by the companion")
        folded = packaged_name.casefold()
        if folded in seen:
            raise ValueError(f"duplicate input filename: {packaged_name}")
        seen.add(folded)
        prepared_inputs.append((source, packaged_name))

    required_names = {name.casefold() for _, name in prepared_inputs}
    for required in ("WEB_REVIEW_REQUEST.json", "WEB_RESPONSE_SCHEMA.json"):
        if required.casefold() not in required_names:
            raise ValueError(f"required input is missing: {required}")

    state_dir.mkdir(parents=True, exist_ok=True)
    calls_dir.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{exchange_id}-", dir=state_dir))
    try:
        request_dir = staging / "request"
        (staging / "response").mkdir(parents=True)
        (staging / "validation").mkdir()
        request_dir.mkdir()

        prompt_path = request_dir / prompt_name
        _write_bytes_durable(prompt_path, prompt_text.encode("utf-8"))
        request_files = [_file_record(prompt_path)]

        for source, packaged_name in prepared_inputs:
            target = request_dir / packaged_name
            _copy_verified(source, target)
            request_files.append(_file_record(target))

        governing = _read_json_object(
            request_dir / "WEB_REVIEW_REQUEST.json", "WEB_REVIEW_REQUEST"
        )
        if governing.get("request_id") != request_id:
            raise ValueError("WEB_REVIEW_REQUEST request_id does not match the call")
        _read_json_object(
            request_dir / "WEB_RESPONSE_SCHEMA.json", "WEB_RESPONSE_SCHEMA"
        )

        manifest = {
            "schema_version": 1,
            "exchange_id": exchange_id,
            "request_id": request_id,
            "subject": subject,
            "created_at": now.astimezone(timezone.utc).isoformat(),
            "state": "PREPARED",
            "expected_main_json": expected_main,
            "request_files": request_files,
            "response_dir": "response",
        }
        _write_json_atomic(staging / "EXCHANGE_MANIFEST.json", manifest)
        os.replace(staging, destination)
        return manifest
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise


def list_ready_calls(root: Path) -> list[dict[str, Any]]:
    calls_dir = Path(root).resolve() / "calls"
    if not calls_dir.exists():
        return []
    ready: list[dict[str, Any]] = []
    for manifest_path in calls_dir.glob("*/EXCHANGE_MANIFEST.json"):
        manifest = _read_json_object(manifest_path, "EXCHANGE_MANIFEST")
        if manifest.get("state") == "PREPARED":
            ready.append(manifest)
    return sorted(ready, key=lambda item: item["exchange_id"])


def start_call(
    root: Path,
    exchange_id: str,
    tab_id: int,
    download_baseline: list[int],
) -> dict[str, Any]:
    root = Path(root).resolve()
    if not isinstance(tab_id, int) or isinstance(tab_id, bool) or tab_id < 0:
        raise ValueError("tab_id must be a non-negative integer")
    if not isinstance(download_baseline, list) or any(
        not isinstance(item, int) or item < 0 for item in download_baseline
    ):
        raise ValueError("download_baseline must contain non-negative integers")

    exchange_dir = _exchange_dir(root, exchange_id)
    manifest_path = exchange_dir / "EXCHANGE_MANIFEST.json"
    manifest = _read_json_object(manifest_path, "EXCHANGE_MANIFEST")
    if manifest.get("exchange_id") != exchange_id:
        raise ValueError("exchange manifest identity does not match its directory")
    if manifest.get("state") != "PREPARED":
        raise RuntimeError("call is not prepared")

    with state_lock(root):
        _assert_can_run_alongside(root, exchange_id, tab_id, manifest)
        active = {
            "exchange_id": exchange_id,
            "exchange_path": str(exchange_dir),
            "request_id": manifest["request_id"],
            "expected_main_json": manifest["expected_main_json"],
            "tab_id": tab_id,
            "started_at": datetime.now(timezone.utc).isoformat(),
            "monitoring": True,
            "download_baseline": sorted(set(download_baseline)),
            "observed_download_ids": [],
            "collected_files": [],
        }
        active_path = _active_path_for(root, exchange_id)
        manifest["state"] = "ACTIVE"
        _write_json_atomic(active_path, active)
        try:
            _write_json_atomic(manifest_path, manifest)
        except BaseException:
            active_path.unlink(missing_ok=True)
            raise
    return active


def load_active_calls(root: Path) -> list[dict[str, Any]]:
    """Return every active call, oldest exchange first."""
    root = Path(root).resolve()
    _migrate_legacy_active(root)
    active_dir = _active_dir(root)
    if not active_dir.is_dir():
        return []
    records = [
        _read_json_object(path, "ACTIVE_CALL")
        for path in sorted(active_dir.glob("*.json"))
    ]
    return sorted(records, key=lambda item: str(item.get("exchange_id", "")))


def load_active_call(
    root: Path, exchange_id: str | None = None
) -> dict[str, Any] | None:
    """Return one active call.

    With no exchange_id this returns the single active call when exactly one is
    running, which keeps single-call callers and the manual fallback simple. It
    refuses to guess when several calls are running.
    """
    records = load_active_calls(root)
    if exchange_id is not None:
        for record in records:
            if record.get("exchange_id") == exchange_id:
                return record
        return None
    if not records:
        return None
    if len(records) > 1:
        raise RuntimeError(
            "several calls are active; name one with --exchange: "
            + ", ".join(str(record.get("exchange_id")) for record in records)
        )
    return records[0]


def resume_call(
    root: Path,
    tab_id: int,
    download_baseline: list[int],
    exchange_id: str | None = None,
) -> dict[str, Any]:
    root = Path(root).resolve()
    if not isinstance(tab_id, int) or isinstance(tab_id, bool) or tab_id < 0:
        raise ValueError("tab_id must be a non-negative integer")
    if not isinstance(download_baseline, list) or any(
        not isinstance(item, int) or isinstance(item, bool) or item < 0
        for item in download_baseline
    ):
        raise ValueError("download_baseline must contain non-negative integers")
    with state_lock(root):
        active = load_active_call(root, exchange_id)
        if active is None:
            raise RuntimeError("no call is active")
        for other in load_active_calls(root):
            if (
                other.get("exchange_id") != active["exchange_id"]
                and other.get("tab_id") == tab_id
            ):
                raise RuntimeError(
                    f"tab {tab_id} is already bound to call {other['exchange_id']}"
                )
        active["tab_id"] = tab_id
        active["started_at"] = datetime.now(timezone.utc).isoformat()
        active["monitoring"] = True
        active["download_baseline"] = sorted(set(download_baseline))
        _write_json_atomic(_active_path_for(root, active["exchange_id"]), active)
    return active


def stop_call(root: Path, exchange_id: str | None = None) -> dict[str, Any]:
    root = Path(root).resolve()
    with state_lock(root):
        active = load_active_call(root, exchange_id)
        if active is None:
            raise RuntimeError("no call is active")
        manifest_path = (
            _exchange_dir(root, active["exchange_id"]) / "EXCHANGE_MANIFEST.json"
        )
        manifest = _read_json_object(manifest_path, "EXCHANGE_MANIFEST")
        manifest["state"] = "STOPPED"
        _write_json_atomic(manifest_path, manifest)
        _active_path_for(root, active["exchange_id"]).unlink(missing_ok=True)
    return manifest


def _assert_can_run_alongside(
    root: Path, exchange_id: str, tab_id: int, manifest: dict[str, Any]
) -> None:
    """Refuse a new call that another active call could be confused with.

    Downloads are routed by filename, so two concurrent calls must never expect
    the same main JSON name. Tabs are the attachment binding, so one tab may
    drive only one call.
    """
    expected_main = str(manifest["expected_main_json"]).casefold()
    for other in load_active_calls(root):
        if other.get("exchange_id") == exchange_id:
            raise RuntimeError("this call is already active")
        if other.get("tab_id") == tab_id:
            raise RuntimeError(
                f"tab {tab_id} is already bound to call {other['exchange_id']}"
            )
        if str(other.get("expected_main_json", "")).casefold() == expected_main:
            raise RuntimeError(
                "another active call already expects "
                f"{manifest['expected_main_json']}; concurrent calls need distinct "
                "expected_main_json names so downloads can be routed"
            )


def _active_dir(root: Path) -> Path:
    return root / "state" / "active"


def _active_path_for(root: Path, exchange_id: str) -> Path:
    if not re.fullmatch(r"[0-9A-Za-z_-]+", exchange_id):
        raise ValueError("exchange_id is unsafe")
    return _active_dir(root) / f"{exchange_id}.json"


def _migrate_legacy_active(root: Path) -> None:
    """Move a single-call ACTIVE_CALL.json into the multi-call directory."""
    legacy = _active_path(root)
    if not legacy.is_file():
        return
    record = _read_json_object(legacy, "ACTIVE_CALL")
    exchange_id = str(record.get("exchange_id", ""))
    if not exchange_id:
        legacy.unlink(missing_ok=True)
        return
    target = _active_path_for(root, exchange_id)
    if not target.exists():
        _write_json_atomic(target, record)
    legacy.unlink(missing_ok=True)


def request_paths(root: Path, exchange_id: str) -> list[str]:
    exchange_dir = _exchange_dir(Path(root).resolve(), exchange_id)
    manifest = _read_json_object(
        exchange_dir / "EXCHANGE_MANIFEST.json", "EXCHANGE_MANIFEST"
    )
    paths: list[str] = []
    for item in manifest.get("request_files", []):
        name = _safe_name(str(item.get("filename", "")), "request filename")
        path = (exchange_dir / "request" / name).resolve(strict=True)
        if path.parent != (exchange_dir / "request").resolve():
            raise ValueError("request file escapes the exchange")
        digest, size = _sha256(path)
        if digest != item.get("sha256") or size != item.get("size"):
            raise ValueError(f"request file changed after preparation: {name}")
        paths.append(str(path))
    return paths


def _subject_slug(subject: str) -> str:
    if not subject or "/" in subject or "\\" in subject or subject in {".", ".."}:
        raise ValueError("subject is empty or unsafe")
    slug = re.sub(r"[^a-z0-9]+", "_", subject.casefold()).strip("_")
    if not slug or len(slug) > 80:
        raise ValueError("subject cannot form a safe exchange name")
    return slug


def _safe_name(name: str, label: str) -> str:
    if (
        not name
        or name in {".", ".."}
        or Path(name).name != name
        or "/" in name
        or "\\" in name
        or name.endswith((".", " "))
        or any(ord(character) < 32 for character in name)
    ):
        raise ValueError(f"{label} is unsafe: {name!r}")
    device = name.rstrip(". ").split(".", 1)[0].upper()
    if device in _RESERVED_NAMES:
        raise ValueError(f"{label} uses a reserved Windows name: {name}")
    return name


def _exchange_dir(root: Path, exchange_id: str) -> Path:
    if not re.fullmatch(r"[0-9A-Za-z_-]+", exchange_id):
        raise ValueError("exchange_id is unsafe")
    calls_dir = (root / "calls").resolve()
    exchange = (calls_dir / exchange_id).resolve()
    if exchange.parent != calls_dir or not exchange.is_dir():
        raise FileNotFoundError(f"exchange does not exist: {exchange_id}")
    return exchange


def _active_path(root: Path) -> Path:
    return root / "state" / "ACTIVE_CALL.json"


def _read_json_object(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError(f"{label} is not valid JSON: {path.name}") from error
    if not isinstance(value, dict):
        raise ValueError(f"{label} must contain a JSON object")
    return value


def _write_json_atomic(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}-", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            json.dump(value, stream, ensure_ascii=False, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _write_bytes_durable(path: Path, contents: bytes) -> None:
    with path.open("xb") as stream:
        stream.write(contents)
        stream.flush()
        os.fsync(stream.fileno())


def _copy_verified(source: Path, destination: Path) -> None:
    before_digest, before_size = _sha256(source)
    with source.open("rb") as incoming, destination.open("xb") as outgoing:
        shutil.copyfileobj(incoming, outgoing)
        outgoing.flush()
        os.fsync(outgoing.fileno())
    after_digest, after_size = _sha256(source)
    copied_digest, copied_size = _sha256(destination)
    if (
        before_digest != after_digest
        or before_size != after_size
        or before_digest != copied_digest
        or before_size != copied_size
    ):
        destination.unlink(missing_ok=True)
        raise RuntimeError(f"input changed while it was copied: {source.name}")


def _sha256(path: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
            size += len(chunk)
    return digest.hexdigest(), size


def _file_record(path: Path) -> dict[str, Any]:
    digest, size = _sha256(path)
    return {"filename": path.name, "size": size, "sha256": digest}
